export type EmergencySector = "police" | "ambulance" | "fire" | "rescue" | "disaster";

export interface EmergencyContact {
  id: string;
  name: string;
  number: string;
  sector: EmergencySector;
  description: string;
  available: string;
  county?: string;
  verified: boolean;
  isTollFree?: boolean;
}

export const EMERGENCY_CONTACTS: EmergencyContact[] = [
  // === NATIONAL EMERGENCY ===
  {
    id: "nat1",
    name: "National Emergency (All Services)",
    number: "999",
    sector: "police",
    description: "Police, fire, ambulance — single national emergency line",
    available: "24/7",
    verified: true,
    isTollFree: true,
  },
  {
    id: "nat2",
    name: "National Emergency Line",
    number: "112",
    sector: "police",
    description: "Works on all mobile networks including no-credit phones",
    available: "24/7",
    verified: true,
    isTollFree: true,
  },

  // === POLICE ===
  {
    id: "pol1",
    name: "Kenya Police Toll-Free Hotline",
    number: "0800 722 203",
    sector: "police",
    description: "National police helpline — free from any network",
    available: "24/7",
    verified: true,
    isTollFree: true,
  },
  {
    id: "pol2",
    name: "Nairobi Police Command",
    number: "020 340000",
    sector: "police",
    description: "Nairobi County police headquarters",
    available: "24/7",
    county: "Nairobi",
    verified: true,
  },
  {
    id: "pol3",
    name: "Mombasa Police Headquarters",
    number: "041 2220551",
    sector: "police",
    description: "Mombasa County police headquarters",
    available: "24/7",
    county: "Mombasa",
    verified: true,
  },
  {
    id: "pol4",
    name: "Kisumu Police HQ",
    number: "",
    sector: "police",
    description: "Kisumu County police headquarters — contact to be updated",
    available: "24/7",
    county: "Kisumu",
    verified: false,
  },
  {
    id: "pol5",
    name: "Nakuru Police",
    number: "",
    sector: "police",
    description: "Nakuru County police headquarters — contact to be updated",
    available: "24/7",
    county: "Nakuru",
    verified: false,
  },
  {
    id: "pol6",
    name: "Eldoret Police",
    number: "",
    sector: "police",
    description: "Uasin Gishu County police headquarters — contact to be updated",
    available: "24/7",
    county: "Uasin Gishu",
    verified: false,
  },
  {
    id: "pol7",
    name: "DCI — Directorate of Criminal Investigations",
    number: "0800 722 203",
    sector: "police",
    description: "Report crime, tips, and criminal investigations — toll-free",
    available: "24/7",
    verified: true,
    isTollFree: true,
  },
  {
    id: "pol8",
    name: "EACC Anti-Corruption Hotline",
    number: "0800 720 380",
    sector: "police",
    description: "Ethics & Anti-Corruption Commission — free tip line",
    available: "24/7",
    verified: true,
    isTollFree: true,
  },
  {
    id: "pol9",
    name: "NTSA Accident Reporting",
    number: "0800 723 500",
    sector: "police",
    description: "National Transport & Safety Authority — report road accidents",
    available: "24/7",
    verified: true,
    isTollFree: true,
  },

  // === AMBULANCE ===
  {
    id: "amb1",
    name: "Kenya Red Cross Ambulance",
    number: "1199",
    sector: "ambulance",
    description: "Free ambulance and emergency medical response nationwide",
    available: "24/7",
    verified: true,
    isTollFree: true,
  },
  {
    id: "amb2",
    name: "St John Ambulance Kenya",
    number: "020 2210000",
    sector: "ambulance",
    description: "First aid and ambulance services — Nairobi and major towns",
    available: "24/7",
    verified: true,
  },
  {
    id: "amb3",
    name: "AMREF Flying Doctors",
    number: "020 6994000",
    sector: "ambulance",
    description: "Air ambulance and critical care evacuation across East Africa",
    available: "24/7",
    verified: true,
  },
  {
    id: "amb4",
    name: "AAR Healthcare Ambulance",
    number: "0709 866 000",
    sector: "ambulance",
    description: "Emergency ambulance and medical rescue services",
    available: "24/7",
    verified: true,
  },
  {
    id: "amb5",
    name: "Nairobi Hospital Emergency",
    number: "020 2845000",
    sector: "ambulance",
    description: "24-hour emergency medical services and ambulance dispatch",
    available: "24/7",
    county: "Nairobi",
    verified: true,
  },
  {
    id: "amb6",
    name: "Aga Khan Hospital Ambulance (Nairobi)",
    number: "020 3662000",
    sector: "ambulance",
    description: "Emergency ambulance dispatch — Aga Khan University Hospital",
    available: "24/7",
    county: "Nairobi",
    verified: true,
  },
  {
    id: "amb7",
    name: "Coast General Hospital Ambulance",
    number: "041 2314201",
    sector: "ambulance",
    description: "Emergency ambulance — Mombasa and the Coast region",
    available: "24/7",
    county: "Mombasa",
    verified: true,
  },
  {
    id: "amb8",
    name: "MTRH Ambulance (Eldoret)",
    number: "053 2033471",
    sector: "ambulance",
    description: "Emergency ambulance — Rift Valley and Western Kenya",
    available: "24/7",
    county: "Uasin Gishu",
    verified: true,
  },

  // === FIRE BRIGADE ===
  {
    id: "fire1",
    name: "Nairobi Fire Brigade",
    number: "020 2222181",
    sector: "fire",
    description: "Nairobi County fire and rescue services",
    available: "24/7",
    county: "Nairobi",
    verified: true,
  },
  {
    id: "fire2",
    name: "Nairobi Fire (Secondary Line)",
    number: "020 2222182",
    sector: "fire",
    description: "Alternative emergency line — Nairobi fire services",
    available: "24/7",
    county: "Nairobi",
    verified: true,
  },
  {
    id: "fire3",
    name: "Mombasa Fire Brigade",
    number: "041 2222024",
    sector: "fire",
    description: "Mombasa County fire and rescue services",
    available: "24/7",
    county: "Mombasa",
    verified: true,
  },
  {
    id: "fire4",
    name: "Kisumu Fire Station",
    number: "",
    sector: "fire",
    description: "Kisumu County fire and rescue — contact to be updated",
    available: "24/7",
    county: "Kisumu",
    verified: false,
  },
  {
    id: "fire5",
    name: "Nakuru Fire Brigade",
    number: "",
    sector: "fire",
    description: "Nakuru County fire and rescue — contact to be updated",
    available: "24/7",
    county: "Nakuru",
    verified: false,
  },
  {
    id: "fire6",
    name: "Eldoret Fire Brigade",
    number: "",
    sector: "fire",
    description: "Uasin Gishu County fire and rescue — contact to be updated",
    available: "24/7",
    county: "Uasin Gishu",
    verified: false,
  },
  {
    id: "fire7",
    name: "KFS Forest Fire Emergency",
    number: "0800 723 774",
    sector: "fire",
    description: "Kenya Forest Service — report forest fires nationwide",
    available: "24/7",
    verified: true,
    isTollFree: true,
  },

  // === DISASTER / RESCUE ===
  {
    id: "dis1",
    name: "National Disaster Operations Centre",
    number: "0800 723 225",
    sector: "disaster",
    description: "Kenya NDOC — flood, drought, landslide, and disaster response",
    available: "24/7",
    verified: true,
    isTollFree: true,
  },
  {
    id: "dis2",
    name: "Kenya Red Cross Disaster Response",
    number: "1199",
    sector: "disaster",
    description: "Disaster relief, search & rescue, and evacuation support",
    available: "24/7",
    verified: true,
    isTollFree: true,
  },
  {
    id: "dis3",
    name: "Kenya Coast Guard / Marine Rescue",
    number: "",
    sector: "disaster",
    description: "Maritime search and rescue — Indian Ocean coast — contact to be updated",
    available: "24/7",
    county: "Mombasa",
    verified: false,
  },
  {
    id: "dis4",
    name: "NEMA Environmental Emergency",
    number: "020 2710574",
    sector: "disaster",
    description: "National Environment Mgmt. Authority — chemical spills, pollution",
    available: "24/7",
    verified: true,
  },
];
