uploads = []
outputs = []

[[generated]]
id = "k1i93qiAa6TqNIjx1a6OY"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "rescue connect app icon"

[[generated]]
id = "OF4CHOJFXdFBw7evq9PL-"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "ambulance splash screen"

[[generated]]
id = "3YcJTKBWgh_yIKHltYEqh"
uri = "file://artifacts/mobile/assets/images/splash-ambulance.png"
type = "image"
title = "Kenyan ambulance splash screen background"
